services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Autoload all services
  OliverKroener\Helpers\:
    resource: '../Classes/*'

  OliverKroener\Helpers\Service\SiteRootService:
    public: true
    autowire: true
    autoconfigure: true
    tags: ['singleton']